name: Test

on:
  push:
    branches: [ main, next, develop ]
  pull_request:
    branches: [ main, next, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Generate code
        run: |
          go generate -skip="mockgen" ./...
          go generate -run="mockgen" ./...

      - name: Initialize permissions.json
        run: |
            cat <<EOF > permissions/permissions.json
            {
              "skip": true,
              "endpoints": []
            }
            EOF 

      - name: Create tmp directory
        run: mkdir -p tmp

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=5m

      - name: Run tests
        env:
          GO_ENV: test
        run: make test

      - name: Generate coverage report
        env:
          GO_ENV: test
        run: make coverage

      - name: Check coverage
        run: make coverage.check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./tmp/cover.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: savioruz/oil
